on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  benchmark:
    name: Run sourmash commands over various versions
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: sourmash_resources
          environment-file: environment.yml
      - name: Run snakemake pipeline
        shell: bash -l {0}
        run: snakemake --use-conda -j 1
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2.10.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: plots
